### ISSUE TITLE
Add meta data for Facebook share

### ISSUE THREAD

**Issue by mattlo** [innovadiv/innovadiv-com-interim#11]
Currently when you share innovadiv.com, its distorted. Using meta data should resolve this https://developers.facebook.com/docs/sharing/best-practices

**Comment by lscullark** [comment]
![screen shot 2015-04-23 at 2 48 52 pm](https://cloud.githubusercontent.com/assets/10977882/7306037/0c1af230-e9c8-11e4-819b-1b2107e4d0f8.png)

**Comment by mattlo** [comment]
This is done

To test, you can use https://developers.facebook.com/tools/debug/og/object/ and debug the output info

Here's the new screenshot:
![screen shot 2015-04-27 at 6 21 56 pm](https://cloud.githubusercontent.com/assets/1714244/7359917/52068986-ed0a-11e4-81b4-dd134f5d6a3e.png)

The distortion around the logo is something unavoidable: We'll probably have to spend time working with FB to avoid reducing quality on their end. http://lockergnome.net/questions/137130/solid-background-images-distorted-on-facebook.html

**Comment by mattlo** [comment]
also for proof, this is the raw image we use http://innovadiv.com/images/logo-red.jpg
